export const types = Object.freeze({
  TODOS_START_FETCHING: 'TODOS_START_FETCHING',
  TODOS_STOP_FETCHING: 'TODOS_STOP_FETCHING',
  TODOS_FILL: 'TODOS_FILL',
  TODOS_SET_FETCHING_ERROR: 'TODOS_SET_FETCHING_ERROR',
  TODOS_FETCH_ASYNC: 'TODOS_FETCH_ASYNC',
});
